//! Lexer implementation

use std::{collections::VecDeque};

use crate::{atn::ATN, lex::{token::{TokenChannel, Token, TokenType}}};

#[derive(Debug)]
struct LexerPosition {
    pub absolute: usize,
    pub line: usize,
    pub char_position_in_line: usize,
}

pub enum LexerAction {
    LexerChannelAction(i32),
    LexerCustomAction {
        rule_index: i32,
        action_index: i32,
    },
    LexerModeAction(i32),
    LexerMoreAction,
    LexerPopModeAction,
    LexerPushModeAction(i32),
    LexerSkipAction,
    LexerTypeAction(i32),
    LexerIndexedCustomAction {
        offset: isize,
        action: Box<LexerAction>,
    },
}

/// Default implementation of Lexer
///
/// Public fields in this struct are intended to be used by embedded actions
#[allow(missing_docs)]
pub struct Lexer<'input> {
    input: Vec<char>,

    // position: LexerPosition,
    atn: ATN,
    
    // error_listeners: Vec<Box<dyn ErrorListener<'input, Self>>>,

    pos: usize,

    /// Overrides token type emitted by lexer for current token
    token_type: TokenType,

    hit_eof: bool,
    /// Channel lexer is currently assigning tokens to
    channel: TokenChannel,
    /// stack of modes, which is used for pushMode,popMode lexer actions
    mode_stack: VecDeque<LexerMode>,
    mode: LexerMode,

    /// Make it `Some` to override token that is currently being generated by lexer
    force_next_token: Option<Token<'input>>,
}

pub enum LexerMode {
    Default,

    /// Special token type to indicate that lexer should continue current token on next iteration
    More,

    /// Special token type to indicate that lexer should not return current token
    /// usually used to skip whitespaces and comments
    Skip
}

pub(crate) const LEXER_MIN_CHAR_VALUE: usize = 0x0000;
pub(crate) const LEXER_MAX_CHAR_VALUE: usize = 0x10FFFF;

impl<'input> Lexer<'input>
{
    /// Creates new lexer instance
    pub fn new(
        input: &'input str,
        atn: ATN
    ) -> Self {
        Self {
            atn,
            input: input.chars().collect(),

            pos: 0,
            token_type: TokenType::Invalid,
            force_next_token: None,
            hit_eof: false,
            channel: super::token::TokenChannel::Default,
            //            token_factory_source_pair: None,
            mode_stack: VecDeque::new(),
            mode: LexerMode::Default,
        }
    }
    
    fn look_ahead(&self, by: usize) -> Option<char> {
        self.input.get(by + self.pos).cloned()
    }
}